kind: pipeline
type: docker
name: amd64_build

platform:
  os: linux
  arch: amd64

steps:
- name: run_python_unit_test
  image: python:3.7.4-alpine3.10
  commands:
  - pip install -r requirements.txt
  - coverage run -m unittest -b
  - codecov --commit=$DRONE_COMMIT_SHA
  environment:
    TEST_FILES_LOCATION: test/test_files
    CODECOV_TOKEN:
      from_secret: codecov_token

- name: docker_build_version
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: nebulaorchestrator/drone-nebula
    auto_tag: true
    auto_tag_suffix: -linux-amd64

---
kind: pipeline
type: docker
name: arm64_build

platform:
  os: linux
  arch: arm64

steps:
- name: run_python_unit_test
  image: python:3.7.4-alpine3.10
  commands:
  - pip install -r requirements.txt
  - coverage run -m unittest
  - codecov --commit=$DRONE_COMMIT_SHA
  environment:
    TEST_FILES_LOCATION: test/test_files
    CODECOV_TOKEN:
      from_secret: codecov_token

- name: docker_build_version
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: nebulaorchestrator/drone-nebula
    auto_tag: true
    auto_tag_suffix: -linux-arm64

---
kind: pipeline
type: docker
name: arm_build

platform:
  os: linux
  arch: arm

steps:
- name: run_python_unit_test
  image: python:3.7.4-alpine3.10
  commands:
  - pip install -r requirements.txt
  - coverage run -m unittest
  - codecov --commit=$DRONE_COMMIT_SHA
  environment:
    TEST_FILES_LOCATION: test/test_files
    CODECOV_TOKEN:
      from_secret: codecov_token

- name: docker_build_version
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: nebulaorchestrator/drone-nebula
    auto_tag: true
    auto_tag_suffix: -linux-arm

---
kind: pipeline
type: docker
name: publish_docker_manifest

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target:  nebulaorchestrator/drone-nebula:${DRONE_SEMVER}
    template: nebulaorchestrator/drone-nebula:${DRONE_SEMVER}-OS-ARCH
    platforms:
      - linux/amd64
      - linux/arm64

trigger:
  event:
    include:
    - tag

---
kind: pipeline
type: docker
name: publish_docker_manifest_push

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target:  nebulaorchestrator/drone-nebula
    template: nebulaorchestrator/drone-nebula:latest-OS-ARCH
    platforms:
      - linux/amd64
      - linux/arm64

trigger:
  event:
    include:
    - push

depends_on:
- amd64_build
- arm64_build
- arm_build
